apiVersion: v1
kind: Namespace
metadata:
  name: flink-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobmanager
  namespace: flink-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobmanager
  template:
    metadata:
      labels:
        app: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: flink:1.16
          command: ["jobmanager"]
          ports:
            - containerPort: 8081
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "jobmanager"
---
apiVersion: v1
kind: Service
metadata:
  name: jobmanager
  namespace: flink-namespace
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
  namespace: flink-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: flink:1.16
          command: ["taskmanager"]
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "jobmanager"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-job
  namespace: flink-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-job
  template:
    metadata:
      labels:
        app: python-job
    spec:
      containers:
        - name: python-job
          image: your-python-image:latest  # Update this with your actual image name
          command: ["python", "/opt/flink/jobs/job.py"]
          volumeMounts:
            - name: flink-jobs
              mountPath: /opt/flink/jobs
      volumes:
        - name: flink-jobs
          hostPath:
            path: ./flink # Update this with your actual path to the jobs

