version: '3.8'

services:
  flink-jobmanager:
    build:  # Use Dockerfile in the current directory
      context: .
      dockerfile: Dockerfile
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    networks:
      - kafka_network
    volumes:
      - ./flink-sql-connector-kafka_2.12-1.14.0.jar:/opt/flink/lib/flink-sql-connector-kafka_2.12-1.14.0.jar  # Mount the JAR file
      - ./data/trading_data:/opt/flink/jobs/data/trading_data 
      - ./flink-sql-connector-elasticsearch7-3.0.1-1.17.jar:/opt/flink/lib/flink-connector-elasticsearch.jar

  flink-taskmanager:
    build:  # Use Dockerfile in the current directory
      context: .
      dockerfile: Dockerfile
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 4  # Set the number of task slots
      FLINK_PROPERTIES: "taskmanager.numberOfTaskSlots=4"
    depends_on:
      - flink-jobmanager
    command: taskmanager
    networks:
      - kafka_network
      - elastic_network
    volumes:
      - ./flink-sql-connector-kafka_2.12-1.14.0.jar:/opt/flink/lib/flink-sql-connector-kafka_2.12-1.14.0.jar  # Mount the JAR file
      - ./data/trading_data:/opt/flink/jobs/data/trading_data
      - ./flink-sql-connector-elasticsearch7-3.0.1-1.17.jar:/opt/flink/lib/flink-connector-elasticsearch.jar

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=password123
    ports:
      - "9200:9200"
    networks:
      - elastic_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    ports:
      - "5601:5601"
    networks:
      - elastic_network
    depends_on:
      - elasticsearch

networks:
  kafka_network:
    driver: bridge
  elastic_network:
    driver: bridge
