version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  flink-jobmanager:
    build:  # Use Dockerfile in the current directory
      context: .
      dockerfile: Dockerfile
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    networks:
      - kafka_network
    volumes:
      - ./flink-sql-connector-kafka-3.3.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.20.jar  # Mount the JAR file
      - ./data/trading_data:/opt/flink/jobs/data/trading_data 
      - ./flink-sql-connector-elasticsearch7-3.0.1-1.17.jar:/opt/flink/lib/flink-connector-elasticsearch.jar
      - /tmp:/tmp
    restart: always 
  flink-taskmanager:
    build:  # Use Dockerfile in the current directory
      context: .
      dockerfile: Dockerfile
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 4  # Set the number of task slots
      FLINK_PROPERTIES: "taskmanager.numberOfTaskSlots=4"
    depends_on:
      - flink-jobmanager
    command: taskmanager
    networks:
      - kafka_network
      - elastic_network
    volumes:
      - ./flink-sql-connector-kafka-3.3.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.20.jar  # Mount the JAR file
      - ./data/trading_data:/opt/flink/jobs/data/trading_data
      - ./flink-sql-connector-elasticsearch7-3.0.1-1.17.jar:/opt/flink/lib/flink-connector-elasticsearch.jar
       - /tmp:/tmp
    restart: always  
  stream-emulator:
    build: .
    volumes:
      - ./data:/opt/flink/jobs/data
      - ./:/usr/src/app  # Mount the entire project directory
    command: ["./wait-for-it.sh", "kafka:9092", "--", "./retry_stream_emulator.sh"]
    depends_on:
      - kafka
    networks:
      - kafka_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=password123
    ports:
      - "9200:9200"
    networks:
      - elastic_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    ports:
      - "5601:5601"
    networks:
      - elastic_network
    depends_on:
      - elasticsearch

networks:
  kafka_network:
    driver: bridge
  elastic_network:
    driver: bridge
