version: "3.7"
services:
  jobmanager:
    image: flink:1.16
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink-network

  taskmanager:
    image: flink:1.16
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink-network
    deploy:
      replicas: 2

  python-job:
    build: .
    depends_on:
      - jobmanager
      - taskmanager
    networks:
      - flink-network
    volumes:
      - ./flink:/opt/flink/jobs
    command: "python /opt/flink/jobs/job.py"

networks:
  flink-network:
    driver: bridge
