{
 "title": "Finanacial dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Financial dashboard indexes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ticker_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ticker_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"ISCIT.NL\" or r[\"symbol\"]==\"IUBBB.FR\" or r[\"symbol\"]== \"IVLED.FR\" or r[\"symbol\"]==\"A3CLUN.ETR\")\n  |> group(columns: [\"symbol\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n"
    }
   ]
  },
  {
   "title": "Latest buy and sell decisons",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ticker_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ema_data\")\n  |> filter(fn: (r) => r[\"advice\"] == \"Buy\" or r[\"advice\"] == \"Sell\")\n  |> sort(columns: [\"advice_timestamp\"], desc: true)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) }))  // Ensure _value is converted to float\n  |> group(columns: [\"symbol\"])  // Group by symbol to apply unique to each symbol\n  |> unique(column: \"symbol\")  // Get the latest advice for each symbol\n  |> group()  // Ungroup to handle the final dataset as a whole\n  |> sort(columns: [\"advice_timestamp\"], desc: true)  // Sort again to keep the overall order\n  |> limit(n: 20)  // Limit to the top 20 results\n  |> keep(columns: [\"symbol\", \"advice_timestamp\", \"advice\"])  // Keep relevant columns\n  |> yield(name: \"latest_advice\")\n"
    }
   ]
  },
  {
   "title": "Financial dashboard equities",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"ticker_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ticker_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"sec_type\"] == \"E\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"FALG.FR\" or r[\"symbol\"] == \"883703.ETR\" or r[\"symbol\"] == \"RWI.NL\" or r[\"symbol\"] == \"MLINM.FR\")\n  |> group(columns: [\"symbol\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Buy and sell decision",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ticker_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ema_data\")\n  |> filter(fn: (r) => r[\"advice\"] == \"Buy\" or r[\"advice\"] == \"Sell\")\n  |> group(columns: [\"advice\"])  \n  |> count()  \n  |> rename(columns: {_value: \"decisions\"})  \n  |> keep(columns: [\"advice\", \"decisions\"])  \n  |> yield(name: \"Buy_and_Sell_Count\")"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } }
 ]
}