{
 "title": "Finanacial dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Finacial dashboard",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ticker_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ticker_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"2ICEU.FR\" or r[\"symbol\"] == \"I10AJ.FR\" or r[\"symbol\"] == \"I1PLU.FR\" or r[\"symbol\"] == \"I2CIT.FR\")\n  |> group(columns: [\"symbol\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Latest buy and sell decisons",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ticker_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ema_data\")\n  |> filter(fn: (r) => r[\"advice\"] == \"Buy\" or r[\"advice\"] == \"Sell\")\n  |> sort(columns: [\"_time\"], desc: true)  \n  |> keep(columns: [\"symbol\", \"_time\", \"advice\"])  \n  |> rename(columns: {_time: \"advice_timestamp\"}) \n  |> group(columns: []) \n  |> limit(n: 10) \n  |> yield(name: \"latest_advice\")\n\n"
    }
   ]
  },
  {
   "title": "Buy and sell decision",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ticker_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ema_data\")\n  |> filter(fn: (r) => r[\"advice\"] == \"Buy\" or r[\"advice\"] == \"Sell\")\n  |> group(columns: [\"advice\"])  \n  |> count()  \n  |> rename(columns: {_value: \"decisions\"})  \n  |> keep(columns: [\"advice\", \"decisions\"])  \n  |> yield(name: \"Buy_and_Sell_Count\")"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } }
 ]
}